global:
  domain: argocd.iamroot.sh

redis-ha:
  enabled: true

controller:
  replicas: 3

server:
  replicas: 3
  service:
    type: LoadBalancer

repoServer:
  replicas: 2

applicationSet:
  replicas: 2